import {
  Article,
  CalendarCheck,
  CaretDown,
  ChartBar,
  ChartLineUp,
  ClipboardText,
  ClockCounterClockwise,
  Calculator,
  Cube,
  Eye,
  FileDashed,
  Folder,
  House,
  ListChecks,
  Money,
  Notebook,
  Package,
  Printer,
  PencilSimpleLine,
  PiggyBank,
  Receipt,
  Scales,
  SignOut,
  ShoppingCart,
  SquaresFour,
  Trash,
  TrendDown,
  TrendUp,
  UserCircle,
  UsersThree,
  X,
} from "@phosphor-icons/react";

export const APP_ICON_WEIGHT = {
  hero: "duotone",
  summary: "duotone",
  nav: "regular",
  action: "bold",
};

export const appIconMap = {
  home: House,
  daily: CalendarCheck,
  menuReports: ListChecks,
  shoppingReports: ShoppingCart,
  foodWaste: Trash,
  priceMonitoring: ChartLineUp,
  beneficiaryGroups: UsersThree,
  weekly: Notebook,
  docs: Folder,
  more: SquaresFour,
  close: X,
  chevronDown: CaretDown,
  user: UserCircle,
  logout: SignOut,
  menu: ClipboardText,
  date: CalendarCheck,
  totalData: ChartBar,
  totalAccumulation: Scales,
  average: TrendUp,
  beneficiaries: UsersThree,
  package: Package,
  packageOpen: Cube,
  activity: ChartBar,
  trendingUp: TrendUp,
  trendingDown: TrendDown,
  database: Article,
  import: Article,
  print: Printer,
  receipt: Receipt,
  money: Money,
  budget: PiggyBank,
  calculator: Calculator,
  empty: FileDashed,
  view: Eye,
  edit: PencilSimpleLine,
  delete: Trash,
  history: ClockCounterClockwise,
};

export function AppIcon({
  name,
  size = 22,
  weight = APP_ICON_WEIGHT.summary,
  className = "",
}) {
  const IconComponent = appIconMap[name] || Article;
  return <IconComponent size={size} weight={weight} className={className} aria-hidden="true" />;
}
